# syntax=docker/dockerfile:1.0-experimental
FROM alpine:latest
LABEL maintainer="louisehong <louisehong4168@gmail.com>"
ARG TARGETPLATFORM
RUN apk update \
    && apk upgrade \
    && apk add --no-cache \
     bash \
     jq \
     bash-completion \
     curl \
     wget


ENTRYPOINT ["/usr/bin/wechat-go"]

WORKDIR /usr/bin/

RUN --mount=target=/build tar xf /build/dist/wechat-go_*_$(echo ${TARGETPLATFORM} | tr '/' '_' | sed -e 's/arm_/arm/').tar.gz

CMD ["--help"]